---
- name: Installieren von Node.js und npm
  include: roles/nodejs_app/tasks/install_nodejs_npm.yml
  when: path_to_app_directory is not defined or path_to_app_directory == ''

- name: Retrieve the list of home directories
  ansible.builtin.command: "ls {{ path_to_app_directory }}"
  register: app_dir
  ignore_errors: true

- name: Kopieren der App-Dateien
  copy:
    src: files/app/
    dest: "{{ path_to_app_directory }}"
  when: app_dir.rc != 0

- name: Installieren von App-Abhängigkeiten
  npm:
    path: "{{ path_to_app_directory }}"
  when: app_dir.rc != 0

- name: Starten der Node.js-App
  command:
    chdir: "{{ path_to_app_directory }}"
    cmd: node app.js
  async: 100
  poll: 0
